### PR TITLE
Port to 1.16 (Requires new branch)

### PR DESCRIPTION
**Pull request by Witixin1512**
Refactor a couple things here and there but use the base classes to make the 1.16 SetEffects port.
Might rewrite the ArmorSet class to use a ZenCodeType.Constructor class but in general, the port is ready.

If there's anything I missed or that you'd like me to do different, please let me know, you can respond to this or through discord (Witixin#5795), I can be found in MMD too.

### CODE REVIEW

**Comment by Lemonszz** [comment]
Oh wow very cool! I'll have a proper look at this soon.

At a glance, I noticed you were including the forge license, readme & credits which should be removed.

I don't have a lot of interest in modding right now myself, so if you'd prefer to release this on your own, I give you full permission, otherwise, I can get you setup on the existing curseforge page if you want.

**Comment by Witixin1512** [comment]
Whoops, I didn't see the forge files, let me just fix that real quick.
 
I personally don't have an issue with uploading it myself, but I believe that out of respect a PR should be offered first.
If afterwards you're not interested in the project anymore or think that I should be the one to maintain it, i'll adapt according to what you prefer. I'd rather you choose the option that you're more comfortable with. Thank you!

**Comment by Lemonszz** [comment]
Hi sorry for taking a while to get back to this.

I do think you should reupload it yourself. I really have no interest in maintaining it,

Probably the best option is to create your own Curseforge page for it, so you don't have to deal with any legacy support. I'll like to the new one on the old page.

If you would prefer to use the old page, that's also fine, just let me know!

Thanks for updating it. I still think it's a cool mod :)

**Comment by Witixin1512** [comment]
Alright, I created the page, but I don't think it will get approved until monday or so (based on CF times)
https://www.curseforge.com/minecraft/mc-mods/armor-set-effects
This is the link for it, I also linked yours.

Thank you for making this mod!

**Pull request closed without merging**
